(include_subdirs unqualified)

(library
 (name example)
 (modes melange)
 (libraries
  ; comment for vertical formatting
  rescript-ssg
  styled-ppx.css
  styled-ppx.emotion)
 (melange.runtime_deps
  src/content.css
  src/css/normalize.css
  src/images/cat.jpeg)
 (preprocess
  (pps melange.ppx reason-react-ppx styled-ppx.lib)))
