(dirs :standard \ node_modules)

(melange.emit
 (target app)
 (libraries rescript-ssg example tests)
 (module_systems
  (es6 mel.mjs)))

(melange.emit
 (alias install)
 (target ssgbin)
 (libraries rescript-ssg)
 (module_systems
  (es6 mel.mjs)))

(install
 (section lib)
 (package rescript-ssg)
 (files
  ; can we put these files to the root of rescript-ssg dir?
  (glob_files ssgbin/node_modules/melange/*.mjs)
  (glob_files ssgbin/node_modules/melange.belt/*.mjs)
  (glob_files ssgbin/node_modules/melange.dom/*.mjs)
  (glob_files ssgbin/node_modules/melange.js/*.mjs)
  (glob_files ssgbin/node_modules/reason-react/*.mjs)
  (glob_files ssgbin/node_modules/rescript-ssg.ssg/*.mjs)
  (glob_files ssgbin/node_modules/rescript-ssg.ssg/bindings/*.mjs)))

(install
 (section libexec)
 (package rescript-ssg)
 (files
  (glob_files ssgbin/node_modules/rescript-ssg.ssg/js/bin.mjs)))
