opam-version: "2.0"
name: "rescript-ssg"
synopsis: "Rescript React static site generator"
maintainer: "Denis Strelkov <strelkov.d.d@gmail.com>"
authors: "Denis Strelkov <strelkov.d.d@gmail.com>"
homepage: "https://github.com/denis-ok/rescript-ssg/"
doc: "https://github.com/denis-ok/rescript-ssg/"
bug-reports: "https://github.com/denis-ok/rescript-ssg/issues"
dev-repo: "git+https://github.com/denis-ok/rescript-ssg.git"
depends: [
  "dune" {>= "3.8"}
  "ocaml" {>= "5.1.0"}
  "melange" {>= "3.0.0"}
  "reason" {>= "3.11.0"}
  "reason-react" {>= "0.14.0"}
  "reason-react-ppx"
  "server-reason-react"
  "styled-ppx" # only used for the example
  "ocaml-lsp-server" {with-dev-setup}
  "ocamlformat" {with-dev-setup}
  "odoc" {with-doc}
]
build: [
  ["dune" "subst"] {dev}
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
    "@doc" {with-doc}
  ]
]
pin-depends: [
  ["server-reason-react.dev" "https://github.com/ml-in-barcelona/server-reason-react/archive/b8756a5c71345e5e8f087a9ec7209b43a066d5f0.tar.gz"]
  ["styled-ppx.dev" "https://github.com/davesnx/styled-ppx/archive/ec69e98cebfe64bed73a30cbc73c4560319acf93.tar.gz"]
]
