(include_subdirs unqualified)

(melange.emit
 (target node)
 (alias main)
 (libraries rescript-ssg reason-react melange-fest)
 (modules
  NodeTest
  FestTests
  Tests
  TestPage
  TestPageWithData
  TestWrapper
  TestWrapperWithData)
 (preprocess
  (pps melange.ppx reason-react-ppx))
 (module_systems
  (es6 mjs)))

(rule
 (alias runtest)
 (deps
  (alias_rec main)
  (:input %{dep:./node/tests/FestTests.mjs}))
 (action
  (run node --test %{input})))

(rule
 (alias runtest)
 (deps
  (alias_rec main)
  (:input %{dep:./node/tests/Tests.mjs}))
 (action
  (setenv
   PROJECT_ROOT_DIR
   %{workspace_root}
   (chdir
    %{workspace_root}
    (run node --test %{input})))))
