name: rescript-ssg

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 16.16.0
      uses: actions/setup-node@v1
      with:
        node-version: '16.16.0'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: make build
